name: simple_gradient_text
description: Create fast and simple gradient texts, whether linear or radial, you just decide the colors and the text to display, very easy.
version: 1.3.0
repository: https://github.com/astudilloalex/flutter_gradient_text

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
